### ISSUE TITLE
USB audio device volume control does not work but EQ does

### ISSUE THREAD

**Issue by Papa2Cherries** [romankisil/eqMac2#30]
I am using a FastTrack Pro usb out and the equalizer of eqMac2 works as intended and the volume appears to work visually, however it does not actually.  Strangely, the volume can be muted/turned up (to one notch)/turned down (to zero notches) by the keyboard but none actually affect the volume.  If i drag the volume slider in the right click menu it can slide to whatever position I wish, but does not affect the volume.  Nor does the Balance.  on 10.12.6.  Unfortunatly I am not sure how to retroactively change the label to bug; I apologize for not reading the reporting guidelines 5 minutes ago when I first read this

**Comment by romankisil** [comment]
Thanks for the report. Can you please open "Audio MIDI Setup" app on your Mac (It in Other folder in Launchpad) select you USB audio device and send me a screenshot like this:
![screen shot 2017-08-06 at 12 29 26](https://user-images.githubusercontent.com/8472525/29002815-ed577f58-7aa2-11e7-9353-6fe85ad717f6.png)

**Comment by Papa2Cherries** [comment]
![screen shot 2017-08-06 at 6 31 34 am](https://user-images.githubusercontent.com/13307464/29002829-f0d58648-7a70-11e7-8570-1a997f9daf4c.png)

**Comment by romankisil** [comment]
Select FastTrack Pro please (both of them, so 2 screenshots if possible)

**Comment by romankisil** [comment]
actually just the one that has 4 outs

**Comment by Papa2Cherries** [comment]
yeah i noticed that after you wrote that, had started too but you beat me to the punch :)

![screen shot 2017-08-06 at 6 33 23 am](https://user-images.githubusercontent.com/13307464/29002839-2bc8cb70-7a71-11e7-9d76-fdecf78df4f5.png)

![screen shot 2017-08-06 at 6 33 47 am](https://user-images.githubusercontent.com/13307464/29002843-3b838d70-7a71-11e7-93dc-4482b2718bdd.png)

**Comment by romankisil** [comment]
It seems like the controls are disabled. How do you change the volume on them without eqMac2 running?

**Comment by Papa2Cherries** [comment]
physically, ill get you a screenshot.

**Comment by Papa2Cherries** [comment]
top is back side, bottom is front.  It is an M-audio Fasttrack pro

![fasttrackpro_front-rear](https://user-images.githubusercontent.com/13307464/29002862-af345c18-7a71-11e7-8b0e-5f78343a830c.jpg)

**Comment by romankisil** [comment]
I guess you can still use it to change Volume, but problem for you is that the Volume won't be maxed out on the Software side. In a future update I will make it check if device has any software volume controls and if not just max out the volume. For now I guess this should work as a work around:
Switch to built-in device, max out your volume, and then switch to FastTrack.

**Comment by Papa2Cherries** [comment]
the volume controls do not affect the actual output, it stays the same volume if i have it to zero/1 notch/muted, the volume always is on and the same amount to the speakers

**Comment by Papa2Cherries** [comment]
I mean the software notches

**Comment by Papa2Cherries** [comment]
I've tried two different macs, one with an older OS, 10.11.2 and it still behaves the same way.  nothing software controls the actual volume output,(ie keyboard volume controls nor the slider after right clicking eqmac2) but the physical nob on the fasttrack device does

**Comment by romankisil** [comment]
So what's the issue if you can control it with the physical knob? Just the incorrect displaying of Volume HUD?

**Comment by Papa2Cherries** [comment]
The hope of this project was to be able to control the usb audio out via keyboard controls.  Let me ask you this, with other usb audio out devices, is this software supposed to be able to control the volume with the f10 f11 and f12 volume controls?  This applicable benefits and uses go much more in depth for my situation, but If usb volume control is something that is supposed to work, then I may be investing in a new usb audio out device in the future.  unfortunately at this time, I only have the one device, but I may be investing in others that do not have physical nobs.  At this time, the physical nob is not in a convenient location to adjust easily on the fly.  That said, even if it was convenient, I am hoping that keyboard volume control is a possibility as it is more natural to use.  Basically put, there is the superficial reason I have described of laziness, as well as a MUCH more in depth reason that will help my set up in a more go/no go situation.

**Comment by Papa2Cherries** [comment]
We know that your software is having an intermediary affect as the equalizer is working correctly, just the volume and balance controls do not work, which for my situation is key.

**Comment by Papa2Cherries** [comment]
A little update, I also tried the HDMI output to see if that had volume controls.  It did not.  There was another program called boom that could control volume, although in a choppy delayed sort of way that led much to be desired, which made it unusable, but it did allude to the idea that one could control the volume of both hdmi and usb audio out via keyboard controls.  I will experiment further to see if i can get any usb device to work, but I suppose it would be easier and much quicker if you told me that yes that is an intended feature and you know it to work or no it is not a feature and wont work ever.  Thank you so far for the prompt responses, I hope to make your program even better by this conversation.  I will be available to respond in about 10 hours.  Hope to come back to an answer by then.

**Comment by romankisil** [comment]
Keep hoping

**Comment by romankisil** [comment]
You last sentence was too demanding. Your issue is not really a bug, but rather an enhancement/feature which even OSX doesn't support by default, so to expect some other apps to fix it for you is stretching it quite too far. It might be possible to implement, but this won't be on my priority list until other more important issues are fixed. Maybe someone else will implement it, it's open-source after all :)

**Comment by Papa2Cherries** [comment]
Oh I can see how you thought I was giving you a demanding timeline.  I meant I would be back on in 10 hours to collaborate and further explain any thoughts that may be unclear but that i was hoping for an answer to the question of "is volume adjustment for usb audio devices" something intended or not.  I was not demanding a fix in 10 hours to my specific issue, but I now see the wording could be taken that way.  There are other usb audio devices out there that I could procure if software volume adjustment is an option for them, since I know they have no hardware volume adjustment built in.  As for calling this a bug or feature, whichever floats your boat.  I figured that I would bring it up to your attention and let you decide how to proceed.  I would like to request just a little nudge of endorsement for looking into if this is possible on your end, because I feel that "maybe someone else will implement it" is really just a washing of the hands of the issue so to speak.  I have been waiting for this "feature" for a long while and since your skills seem to be able to create great software in regards to audio enhancements, you telling me if this is a pipe dream or not, even if this is your preliminary finding, would be helpful to me.  I would help with the coding if i knew how, perhaps i will try to understand your process and bring myself up to speed with self teaching. :)  I won't expect a prompt reply on this topic as you said other things are of more pressing matter, but I would like to urge that you do not dismiss this "feature" completely.   Thank you for all that you have done so far.

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
