### ISSUE TITLE
Proposal: port EQ presets from e.g. iTunes

### ISSUE THREAD

**Issue by mvasilkov** [romankisil/eqMac2#4]
Hi Roman,

Amazing project!

I had a suggestion: can we maybe put some presets in by default? (I just looked for the iTunes' default presets, but they don't seem to be stored in a readable format.)

**Comment by romankisil** [comment]
Yes I initially added some by default, but in my opinion they were all garbage. The point is that the user adjusts the EQ bands specifically for his headphones/setup. 
There is a file:
https://github.com/romankisil/eqMac2/blob/master/Source/Common/Presets/defaultPresets.plist
If you want to propose some of your default presets you can put them here :)

**Comment by romankisil** [comment]
Will take the default presets from iTunes and add them in the next update

**Comment by mvasilkov** [comment]
Have you found a good way to export them from iTunes? I'll gladly do the file format conversion work.

**Comment by romankisil** [comment]
Here's what I was just trying to do:
Open iTunes Equaliser Window. Select one of the default presets. Then click on "Make Preset..." from the dropdown menu, name the preset and save. This will create file "~/Library/Preferences/com.apple.iTunes.eq.plist" that stores your custom presets. Inside the plist there is a NSData object which contains the name and the gain information about all your custom presets. Problem is that I don't know what Encoding this NSData was encoded with. So I can't figure out the structure of these Bytes... I tried JSON, NSArray, NSDictionary, NSString, NSUTF8StringEncoding and many others. If you have any ideas please share :)

**Comment by romankisil** [comment]
@mvasilkov turns out that files stores all the default presets as well, not just custom. I can see all the preset names if I convert the Data to Chars

**Comment by mvasilkov** [comment]
Yup, I've seen the names in there too, but the rest of the data was zeroes I think.

I'll take a look at it again though, thanks.

**Comment by romankisil** [comment]
I've managed to pull the data, will post it in a minute

**Comment by romankisil** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist SYSTEM "file://localhost/System/Library/DTDs/PropertyList.dtd">
<plist version="1.0">
<dict>
	<key>Accoustic</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>-0.172916666667</real>
			<real>0.204166666667</real>
			<real>-0.326666666667</real>
			<real>0.04375</real>
			<real>0.379583333333</real>
			<real>0.0729166666667</real>
			<real>0.145833333333</real>
			<real>0.170833333333</real>
			<real>0.147916666667</real>
			<real>0.0895833333333</real>
		</array>
	</dict>
	<key>Bass Booster</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.229166666667</real>
			<real>0.177083333333</real>
			<real>0.145833333333</real>
			<real>0.104166666667</real>
			<real>0.0520833333333</real>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
		</array>
	</dict>
	<key>Bass Reducer</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>-0.229166666667</real>
			<real>-0.177083333333</real>
			<real>-0.145833333333</real>
			<real>-0.104166666667</real>
			<real>-0.0520833333333</real>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
		</array>
	</dict>
	<key>Classic </key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.197916666667</real>
			<real>0.15625</real>
			<real>0.125</real>
			<real>0.104166666667</real>
			<real>-0.0625</real>
			<real>-0.0625</real>
			<integer>0</integer>
			<real>0.09375</real>
			<real>0.135416666667</real>
			<real>0.15625</real>
		</array>
	</dict>
	<key>Dance</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.14875</real>
			<real>0.272916666667</real>
			<real>0.207916666667</real>
			<integer>0</integer>
			<real>0.08</real>
			<real>0.152083333333</real>
			<real>0.214583333333</real>
			<real>0.189166666667</real>
			<real>0.149583333333</real>
			<integer>0</integer>
		</array>
	</dict>
	<key>Deep</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.20625</real>
			<real>0.147916666667</real>
			<real>0.0729166666667</real>
			<real>0.0416666666667</real>
			<real>0.11875</real>
			<real>0.104166666667</real>
			<real>0.0604166666667</real>
			<real>-0.0895833333333</real>
			<real>-0.147916666667</real>
			<real>-0.191666666667</real>
		</array>
	</dict>
	<key>Electronic</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.177083333333</real>
			<real>0.158333333333</real>
			<real>0.05</real>
			<integer>0</integer>
			<real>-0.0895833333333</real>
			<real>0.09375</real>
			<real>0.0354166666667</real>
			<real>0.0520833333333</real>
			<real>0.164583333333</real>
			<real>0.2</real>
		</array>
	</dict>
	<key>Hip-Hop</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.208333333333</real>
			<real>0.177083333333</real>
			<real>0.0625</real>
			<real>0.125</real>
			<real>-0.0416666666667</real>
			<real>-0.0416666666667</real>
			<real>0.0625</real>
			<real>-0.0208333333333</real>
			<real>0.0833333333333</real>
			<real>0.125</real>
		</array>
	</dict>
	<key>Jazz</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.166666666667</real>
			<real>0.125</real>
			<real>0.0625</real>
			<real>0.09375</real>
			<real>-0.0625</real>
			<real>-0.0625</real>
			<integer>0</integer>
			<real>0.0625</real>
			<real>0.125</real>
			<real>0.15625</real>
		</array>
	</dict>
	<key>Latin</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.1875</real>
			<real>0.125</real>
			<integer>0</integer>
			<integer>0</integer>
			<real>-0.0625</real>
			<real>-0.0625</real>
			<real>-0.0625</real>
			<integer>0</integer>
			<real>0.125</real>
			<real>0.1875</real>
		</array>
	</dict>
	<key>Loudness</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.25</real>
			<real>0.166666666667</real>
			<integer>0</integer>
			<integer>0</integer>
			<real>-0.0833333333333</real>
			<integer>0</integer>
			<real>-0.0416666666667</real>
			<real>-0.208333333333</real>
			<real>0.208333333333</real>
			<real>0.0416666666667</real>
		</array>
	</dict>
	<key>Lounge</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>-0.125</real>
			<real>-0.0625</real>
			<real>-0.0208333333333</real>
			<real>0.0625</real>
			<real>0.166666666667</real>
			<real>0.104166666667</real>
			<integer>0</integer>
			<real>-0.0625</real>
			<real>0.0833333333333</real>
			<real>0.0416666666667</real>
		</array>
	</dict>
	<key>Piano</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.125</real>
			<real>0.0833333333333</real>
			<integer>0</integer>
			<real>0.104166666667</real>
			<real>0.125</real>
			<real>0.0625</real>
			<real>0.145833333333</real>
			<real>0.1875</real>
			<real>0.125</real>
			<real>0.145833333333</real>
		</array>
	</dict>
	<key>Pop</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>-0.0625</real>
			<real>-0.0416666666667</real>
			<integer>0</integer>
			<real>0.0833333333333</real>
			<real>0.166666666667</real>
			<real>0.166666666667</real>
			<real>0.0833333333333</real>
			<integer>0</integer>
			<real>-0.0416666666667</real>
			<real>-0.0625</real>
		</array>
	</dict>
	<key>R</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.109166666667</real>
			<real>0.288333333333</real>
			<real>0.235416666667</real>
			<real>0.0554166666667</real>
			<real>-0.09125</real>
			<real>-0.0625</real>
			<real>0.0966666666667</real>
			<real>0.110416666667</real>
			<real>0.125</real>
			<real>0.15625</real>
		</array>
	</dict>
	<key>Rock</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.208333333333</real>
			<real>0.166666666667</real>
			<real>0.125</real>
			<real>0.0625</real>
			<real>-0.0208333333333</real>
			<real>-0.0416666666667</real>
			<real>0.0208333333333</real>
			<real>0.104166666667</real>
			<real>0.145833333333</real>
			<real>0.1875</real>
		</array>
	</dict>
	<key>Small Speakers</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>0.229166666667</real>
			<real>0.177083333333</real>
			<real>0.145833333333</real>
			<real>0.104166666667</real>
			<real>0.0520833333333</real>
			<integer>0</integer>
			<real>-0.0520833333333</real>
			<real>-0.104166666667</real>
			<real>-0.145833333333</real>
			<real>-0.177083333333</real>
		</array>
	</dict>
	<key>Spoken Word</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>-0.144166666667</real>
			<real>-0.0195833333333</real>
			<integer>0</integer>
			<real>0.02875</real>
			<real>0.144166666667</real>
			<real>0.192083333333</real>
			<real>0.201666666667</real>
			<real>0.178333333333</real>
			<real>0.105833333333</real>
			<integer>0</integer>
		</array>
	</dict>
	<key>Treble Booster</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
			<real>0.0520833333333</real>
			<real>0.104166666667</real>
			<real>0.145833333333</real>
			<real>0.177083333333</real>
			<real>0.229166666667</real>
		</array>
	</dict>
	<key>Treble Reducer</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
			<integer>0</integer>
			<real>-0.0520833333333</real>
			<real>-0.104166666667</real>
			<real>-0.145833333333</real>
			<real>-0.177083333333</real>
			<real>-0.229166666667</real>
		</array>
	</dict>
	<key>Vocal Booster</key>
	<dict>
		<key>default</key>
		<true/>
		<key>gains</key>
		<array>
			<real>-0.0625</real>
			<real>-0.125</real>
			<real>-0.125</real>
			<real>0.0625</real>
			<real>0.15625</real>
			<real>0.15625</real>
			<real>0.125</real>
			<real>0.0625</real>
			<integer>0</integer>
			<real>-0.0625</real>
		</array>
	</dict>
</dict>
</plist>
`

**Comment by romankisil** [comment]
added in 16c75b9a669f9e55865a58b3d44a8cdc010a2463

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
